# Must check if some one updated axisRecord.dbd.pod

AXISAUTOGENERATED = documentation/axisRecord.html \
                    AxisSrc/axisRecord.dbd


install: $(AXISAUTOGENERATED)

build: $(AXISAUTOGENERATED)

clean: rmaxisRecordDbd

rmaxisRecordDbd:
	rm -f $(AXISAUTOGENERATED)


$(AXISAUTOGENERATED): \
             AxisSrc/axisRecord.dbd.pod \
             tools/gen_axisRecord_html.sh
	./tools/gen_axisRecord_html.sh


ifdef EPICS_ENV_PATH
ifeq ($(EPICS_MODULES_PATH),/opt/epics/modules)
ifeq ($(EPICS_BASES_PATH),/opt/epics/bases)
include Makefile.EEE
else
include Makefile.epics
endif
else
include Makefile.epics
endif
else
include Makefile.epics
endif
