EXCLUDE_VERSIONS=3.14.12.5
# Temporally removed to speed up
EXCLUDE_ARCHS += eldk

include ${EPICS_ENV_PATH}/module.Makefile

PROJECT=IcePAP

AUTO_DEPENDENCIES = NO
USR_DEPENDENCIES += axisCore,10.2.0


SOURCES = \
  IcePAPApp/src/IcePAPAxis.cpp \
  IcePAPApp/src/IcePAPController.cpp \
  IcePAPApp/src/IcePAPMain.cpp

TEMPLATES = IcePAPApp/Db/IcePAP.template

#MISCS = \
